"""Add calibration fields to sensor

Revision ID: 092f9504d67e
Revises: 2a007f73b496
Create Date: 2025-07-13 03:43:39.809558

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '092f9504d67e'
down_revision = '2a007f73b496'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sensors', schema=None) as batch_op:
        batch_op.add_column(sa.Column('responsavel_tec', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('contato', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('data_calibracao', sa.Date(), nullable=True))
        batch_op.add_column(sa.Column('proxima_calibracao', sa.Date(), nullable=True))
        batch_op.add_column(sa.Column('nomenclatura', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('local_calibracao', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('empresa_calibracao', sa.String(length=100), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sensors', schema=None) as batch_op:
        batch_op.drop_column('empresa_calibracao')
        batch_op.drop_column('local_calibracao')
        batch_op.drop_column('nomenclatura')
        batch_op.drop_column('proxima_calibracao')
        batch_op.drop_column('data_calibracao')
        batch_op.drop_column('contato')
        batch_op.drop_column('responsavel_tec')

    # ### end Alembic commands ###
