"""Adiciona campos contato e email à tabela empresa

Revision ID: 13251446622a
Revises: b27003f61bac
Create Date: 2025-07-13 02:07:25.590625

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '13251446622a'
down_revision = 'b27003f61bac'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('empresa', schema=None) as batch_op:
        batch_op.add_column(sa.Column('contato', sa.String(length=100), nullable=True))
        batch_op.alter_column('email',
               existing_type=sa.VARCHAR(length=100),
               type_=sa.String(length=120),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('empresa', schema=None) as batch_op:
        batch_op.alter_column('email',
               existing_type=sa.String(length=120),
               type_=sa.VARCHAR(length=100),
               existing_nullable=True)
        batch_op.drop_column('contato')

    # ### end Alembic commands ###
