"""Add certificado_path to Sensor

Revision ID: 2a007f73b496
Revises: 13251446622a
Create Date: 2025-07-13 02:27:12.461478

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2a007f73b496'
down_revision = '13251446622a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sensors', schema=None) as batch_op:
        batch_op.add_column(sa.Column('certificado_path', sa.String(length=200), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sensors', schema=None) as batch_op:
        batch_op.drop_column('certificado_path')

    # ### end Alembic commands ###
