"""baseline

Revision ID: 3db227102dc6
Revises: 
Create Date: 2025-07-15 15:47:59.589413

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3db227102dc6'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('empresa',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=100), nullable=False),
    sa.Column('cnpj', sa.String(length=20), nullable=True),
    sa.Column('endereco', sa.String(length=200), nullable=True),
    sa.Column('telefone', sa.String(length=20), nullable=True),
    sa.Column('contato', sa.String(length=100), nullable=True),
    sa.Column('email', sa.String(length=120), nullable=True),
    sa.Column('cidade', sa.String(length=50), nullable=True),
    sa.Column('estado', sa.String(length=2), nullable=True),
    sa.Column('cep', sa.String(length=10), nullable=True),
    sa.Column('criado_em', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('locations',
    sa.Column('location_id', sa.String(length=200), nullable=False),
    sa.Column('date_created', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('location_id')
    )
    op.create_table('products',
    sa.Column('product_id', sa.String(length=200), nullable=False),
    sa.Column('date_created', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('product_id')
    )
    op.create_table('tipos_device',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=100), nullable=False),
    sa.Column('criado_em', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nome')
    )
    op.create_table('tipos_sonda',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=100), nullable=False),
    sa.Column('criado_em', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nome')
    )
    op.create_table('sensors',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=100), nullable=False),
    sa.Column('codigo', sa.String(length=100), nullable=False),
    sa.Column('codigo_sonda', sa.String(length=100), nullable=True),
    sa.Column('empresa', sa.String(length=100), nullable=True),
    sa.Column('tipo_device', sa.Integer(), nullable=True),
    sa.Column('tipo_sonda', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('localizacao', sa.String(length=100), nullable=True),
    sa.Column('estoque_minimo', sa.Integer(), nullable=True),
    sa.Column('criado_em', sa.DateTime(), nullable=True),
    sa.Column('certificado_path', sa.String(length=200), nullable=True),
    sa.Column('responsavel_tec', sa.String(length=100), nullable=True),
    sa.Column('contato', sa.String(length=100), nullable=True),
    sa.Column('data_calibracao', sa.Date(), nullable=True),
    sa.Column('proxima_calibracao', sa.Date(), nullable=True),
    sa.Column('nomenclatura', sa.String(length=100), nullable=True),
    sa.Column('local_calibracao', sa.String(length=100), nullable=True),
    sa.Column('empresa_calibracao', sa.String(length=100), nullable=True),
    sa.ForeignKeyConstraint(['tipo_device'], ['tipos_device.id'], ),
    sa.ForeignKeyConstraint(['tipo_sonda'], ['tipos_sonda.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('codigo')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('sensors')
    op.drop_table('tipos_sonda')
    op.drop_table('tipos_device')
    op.drop_table('products')
    op.drop_table('locations')
    op.drop_table('empresa')
    # ### end Alembic commands ###
