"""add permissions to User

Revision ID: 521a8e66d000
Revises: c1b02b3502e6
Create Date: 2025-07-18 11:01:08.016657

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '521a8e66d000'
down_revision = 'c1b02b3502e6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('usuarios', schema=None) as batch_op:
        batch_op.add_column(sa.Column('can_view', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('can_edit', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('can_delete', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('can_export', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('usuarios', schema=None) as batch_op:
        batch_op.drop_column('can_export')
        batch_op.drop_column('can_delete')
        batch_op.drop_column('can_edit')
        batch_op.drop_column('can_view')

    # ### end Alembic commands ###
