"""adiciona colunas cnpj/endereco/etc em empresas

Revision ID: 5926735d91d4
Revises: a29b9ec65882
Create Date: 2025-07-15 20:34:14.539132

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5926735d91d4'
down_revision = 'a29b9ec65882'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('empresa')
    with op.batch_alter_table('empresas', schema=None) as batch_op:
        batch_op.add_column(sa.Column('cnpj', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('endereco', sa.String(length=200), nullable=True))
        batch_op.add_column(sa.Column('telefone', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('contato', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('email', sa.String(length=120), nullable=True))
        batch_op.add_column(sa.Column('cep', sa.String(length=10), nullable=True))
        batch_op.add_column(sa.Column('criado_em', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('empresas', schema=None) as batch_op:
        batch_op.drop_column('criado_em')
        batch_op.drop_column('cep')
        batch_op.drop_column('email')
        batch_op.drop_column('contato')
        batch_op.drop_column('telefone')
        batch_op.drop_column('endereco')
        batch_op.drop_column('cnpj')

    op.create_table('empresa',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('nome', sa.VARCHAR(length=100), nullable=False),
    sa.Column('cnpj', sa.VARCHAR(length=20), nullable=True),
    sa.Column('endereco', sa.VARCHAR(length=200), nullable=True),
    sa.Column('telefone', sa.VARCHAR(length=20), nullable=True),
    sa.Column('contato', sa.VARCHAR(length=100), nullable=True),
    sa.Column('email', sa.VARCHAR(length=120), nullable=True),
    sa.Column('cidade', sa.VARCHAR(length=50), nullable=True),
    sa.Column('estado', sa.VARCHAR(length=2), nullable=True),
    sa.Column('cep', sa.VARCHAR(length=10), nullable=True),
    sa.Column('criado_em', sa.DATETIME(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###
