"""parceiros forumario update

Revision ID: 9daf8bca6b42
Revises: 972d92d83868
Create Date: 2025-07-15 23:32:39.725945

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9daf8bca6b42'
down_revision = '972d92d83868'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('parceiros', schema=None) as batch_op:
        batch_op.add_column(sa.Column('cep', sa.String(length=80), nullable=True))
        batch_op.add_column(sa.Column('Rua', sa.String(length=120), nullable=True))
        batch_op.add_column(sa.Column('numero', sa.String(length=14), nullable=True))
        batch_op.add_column(sa.Column('complemento', sa.String(length=40), nullable=True))
        batch_op.alter_column('pix',
               existing_type=sa.VARCHAR(length=120),
               type_=sa.String(length=100),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('parceiros', schema=None) as batch_op:
        batch_op.alter_column('pix',
               existing_type=sa.String(length=100),
               type_=sa.VARCHAR(length=120),
               existing_nullable=True)
        batch_op.drop_column('complemento')
        batch_op.drop_column('numero')
        batch_op.drop_column('Rua')
        batch_op.drop_column('cep')

    # ### end Alembic commands ###
