"""Add dashboard_order to user

Revision ID: c61f6d182d50
Revises: e6e98a1f8766
Create Date: 2025-07-19 00:48:36.897481

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c61f6d182d50'
down_revision = 'e6e98a1f8766'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('usuarios', schema=None) as batch_op:
        batch_op.add_column(sa.Column('dashboard_order', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('usuarios', schema=None) as batch_op:
        batch_op.drop_column('dashboard_order')

    # ### end Alembic commands ###
