"""Adiciona coluna trocar_senha em usuarios

Revision ID: e6e98a1f8766
Revises: 73d16fd09224
Create Date: 2025-07-18 16:47:57.250457

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e6e98a1f8766'
down_revision = '73d16fd09224'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('usuarios', schema=None) as batch_op:
        batch_op.add_column(sa.Column('trocar_senha', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('usuarios', schema=None) as batch_op:
        batch_op.drop_column('trocar_senha')

    # ### end Alembic commands ###
