"""Inicialização local com PostgreSQL

Revision ID: f275daf47450
Revises: 
Create Date: 2025-07-21 11:32:40.670826

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f275daf47450'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('empresas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=120), nullable=False),
    sa.Column('cnpj', sa.String(length=20), nullable=True),
    sa.Column('endereco', sa.String(length=200), nullable=True),
    sa.Column('telefone', sa.String(length=20), nullable=True),
    sa.Column('contato', sa.String(length=100), nullable=True),
    sa.Column('email', sa.String(length=120), nullable=True),
    sa.Column('cidade', sa.String(length=80), nullable=True),
    sa.Column('estado', sa.String(length=2), nullable=True),
    sa.Column('cep', sa.String(length=10), nullable=True),
    sa.Column('criado_em', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nome')
    )
    op.create_table('estados',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('sigla', sa.String(length=2), nullable=False),
    sa.Column('nome', sa.String(length=80), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('sigla')
    )
    op.create_table('locations',
    sa.Column('location_id', sa.String(length=200), nullable=False),
    sa.Column('date_created', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('location_id')
    )
    op.create_table('parceiros',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=120), nullable=False),
    sa.Column('telefone', sa.String(length=40), nullable=True),
    sa.Column('cidade', sa.String(length=80), nullable=True),
    sa.Column('uf', sa.String(length=2), nullable=True),
    sa.Column('cpf', sa.String(length=14), nullable=True),
    sa.Column('pix', sa.String(length=100), nullable=True),
    sa.Column('cep', sa.String(length=80), nullable=True),
    sa.Column('rua', sa.String(length=120), nullable=True),
    sa.Column('numero', sa.String(length=14), nullable=True),
    sa.Column('complemento', sa.String(length=40), nullable=True),
    sa.Column('bairro', sa.String(length=120), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nome')
    )
    op.create_table('products',
    sa.Column('product_id', sa.String(length=200), nullable=False),
    sa.Column('date_created', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('product_id')
    )
    op.create_table('tipos_device',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=100), nullable=False),
    sa.Column('criado_em', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nome')
    )
    op.create_table('tipos_sonda',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=100), nullable=False),
    sa.Column('criado_em', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nome')
    )
    op.create_table('usuarios',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=100), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('senha_hash', sa.String(length=512), nullable=False),
    sa.Column('reset_token', sa.String(length=100), nullable=True),
    sa.Column('permissoes', sa.JSON(), nullable=True),
    sa.Column('can_view', sa.Boolean(), nullable=True),
    sa.Column('can_create', sa.Boolean(), nullable=True),
    sa.Column('can_edit', sa.Boolean(), nullable=True),
    sa.Column('can_delete', sa.Boolean(), nullable=True),
    sa.Column('can_export', sa.Boolean(), nullable=True),
    sa.Column('is_admin', sa.Boolean(), nullable=True),
    sa.Column('trocar_senha', sa.Boolean(), nullable=True),
    sa.Column('dashboard_order', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('municipios',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=120), nullable=False),
    sa.Column('estado_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['estado_id'], ['estados.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('parceiros_empresas',
    sa.Column('parceiro_id', sa.Integer(), nullable=True),
    sa.Column('empresa_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['empresa_id'], ['empresas.id'], ),
    sa.ForeignKeyConstraint(['parceiro_id'], ['parceiros.id'], )
    )
    op.create_table('sensors',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=100), nullable=False),
    sa.Column('codigo', sa.String(length=100), nullable=False),
    sa.Column('codigo_sonda', sa.String(length=100), nullable=True),
    sa.Column('empresa', sa.String(length=100), nullable=True),
    sa.Column('tipo_device', sa.Integer(), nullable=True),
    sa.Column('tipo_sonda', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('localizacao', sa.String(length=100), nullable=True),
    sa.Column('estoque_minimo', sa.Integer(), nullable=True),
    sa.Column('criado_em', sa.DateTime(), nullable=True),
    sa.Column('certificado_path', sa.String(length=200), nullable=True),
    sa.Column('responsavel_tec', sa.String(length=100), nullable=True),
    sa.Column('contato', sa.String(length=100), nullable=True),
    sa.Column('data_calibracao', sa.Date(), nullable=True),
    sa.Column('proxima_calibracao', sa.Date(), nullable=True),
    sa.Column('nomenclatura', sa.String(length=100), nullable=True),
    sa.Column('local_calibracao', sa.String(length=100), nullable=True),
    sa.Column('empresa_calibracao', sa.String(length=100), nullable=True),
    sa.ForeignKeyConstraint(['tipo_device'], ['tipos_device.id'], ),
    sa.ForeignKeyConstraint(['tipo_sonda'], ['tipos_sonda.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('codigo')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('sensors')
    op.drop_table('parceiros_empresas')
    op.drop_table('municipios')
    op.drop_table('usuarios')
    op.drop_table('tipos_sonda')
    op.drop_table('tipos_device')
    op.drop_table('products')
    op.drop_table('parceiros')
    op.drop_table('locations')
    op.drop_table('estados')
    op.drop_table('empresas')
    # ### end Alembic commands ###
